

/*CREATE TABLE `item` ( `id` INT(11) NOT NULL,`name` VARCHAR(50) NULL DEFAULT NULL,`category` VARCHAR(50) NULL DEFAULT NULL,PRIMARY KEY (`id`));*/

/*create table customer (id integer generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), primary key (id));
create table product (id varchar(255) not null, name varchar(255), photo varchar(255), price double not null, quantity integer not null,
status boolean not null, primary key (id));*/

/*create table employee (id integer generated by default as identity, city varchar(255), country varchar(255), dob varchar(255), doj varchar(255),
email varchar(255), emp_id varchar(255), father_name varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255),
phone varchar(255), region varchar(255), salary integer, state varchar(255), zip integer, primary key (id));*/
